# -*- coding: utf-8 -*-
"""DATA_603_Homework_01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F-h3h5nyFlPc1-CUmFmkCH5OFSUKU-_R
"""

"""
DATA 603 - Trustworthy AI - Homework 1: Generalization / Distribution Shift
============================================================================

Experiment: train a ResNet-CIFAR model with ERM on CIFAR-10, then evaluate
it in-distribution (clean CIFAR-10 test set) and out-of-distribution
(CIFAR-10-C corrupted test set). Train two versions -- a baseline and a
version with stronger data augmentation -- to get the "one simple
mitigation" comparison needed for the graduate extension.

DESIGNED FOR GOOGLE COLAB. Paste each "# %%" section into its own cell,
or run the whole thing as a script with `!python cifar_shift_experiment.py`.
"""

# %% [SETUP] Mount drive + imports -------------------------------------------
from google.colab import drive
drive.mount('/content/drive')

import os
import time
import json
import tarfile
import urllib.request

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import torchvision
import torchvision.transforms as T

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {DEVICE}")

# All persistent files (checkpoints, downloaded data, results) live on Drive
# so a Colab disconnect doesn't cost you progress.
DRIVE_ROOT = '/content/drive/MyDrive/data603_hw1'
CIFAR10C_DIR = os.path.join(DRIVE_ROOT, 'CIFAR-10-C')
CKPT_DIR = os.path.join(DRIVE_ROOT, 'checkpoints')
RESULTS_DIR = os.path.join(DRIVE_ROOT, 'results')
for d in (DRIVE_ROOT, CKPT_DIR, RESULTS_DIR):
    os.makedirs(d, exist_ok=True)

SEED = 0
torch.manual_seed(SEED)
np.random.seed(SEED)

# %% [DOWNLOAD] CIFAR-10-C ----------------------------------------------------
# CIFAR-10-C is ~2.9GB. This only needs to run once -- subsequent runs will
# find it already on Drive and skip the download.
CIFAR10C_URL = "https://zenodo.org/record/2535967/files/CIFAR-10-C.tar"
CIFAR10C_TAR = os.path.join(DRIVE_ROOT, 'CIFAR-10-C.tar')

if not os.path.exists(CIFAR10C_DIR):
    if not os.path.exists(CIFAR10C_TAR):
        print("Downloading CIFAR-10-C (~2.9GB, this will take a while)...")
        urllib.request.urlretrieve(CIFAR10C_URL, CIFAR10C_TAR)
    print("Extracting...")
    with tarfile.open(CIFAR10C_TAR) as tf:
        tf.extractall(DRIVE_ROOT)
    print("Done.")
else:
    print("CIFAR-10-C already present, skipping download.")

# Pick a subset of corruption types to evaluate -- running all 15 is wasted
# compute for a 2-page report. These four are commonly used as a
# representative spread (noise, blur, weather, digital).
CORRUPTIONS = ['gaussian_noise', 'motion_blur', 'fog', 'contrast']
SEVERITY = 3  # 1 (mild) to 5 (severe); 3 is a reasonable middle ground

# %% [DATA] Dataset classes ---------------------------------------------------
CIFAR_MEAN = (0.4914, 0.4822, 0.4465)
CIFAR_STD = (0.2470, 0.2435, 0.2616)

# Baseline augmentation: standard, mild
transform_train_baseline = T.Compose([
    T.RandomCrop(32, padding=4),
    T.RandomHorizontalFlip(),
    T.ToTensor(),
    T.Normalize(CIFAR_MEAN, CIFAR_STD),
])

# Stronger augmentation: this is the "mitigation" arm of the experiment
transform_train_augmented = T.Compose([
    T.RandomCrop(32, padding=4),
    T.RandomHorizontalFlip(),
    T.ColorJitter(brightness=0.4, contrast=0.4, saturation=0.4),
    T.RandomErasing(p=0.25, scale=(0.02, 0.15)),
    T.ToTensor(),
    T.Normalize(CIFAR_MEAN, CIFAR_STD),
])
# NOTE: RandomErasing must run on a tensor, so the transform order above is
# slightly wrong for RandomErasing specifically -- fix by moving ToTensor
# before RandomErasing:
transform_train_augmented = T.Compose([
    T.RandomCrop(32, padding=4),
    T.RandomHorizontalFlip(),
    T.ColorJitter(brightness=0.4, contrast=0.4, saturation=0.4),
    T.ToTensor(),
    T.Normalize(CIFAR_MEAN, CIFAR_STD),
    T.RandomErasing(p=0.25, scale=(0.02, 0.15)),
])

transform_test = T.Compose([
    T.ToTensor(),
    T.Normalize(CIFAR_MEAN, CIFAR_STD),
])


class CIFAR10CDataset(Dataset):
    """Loads one corruption type at one severity level from CIFAR-10-C.

    CIFAR-10-C stores each corruption as a single .npy file of shape
    (50000, 32, 32, 3) -- the 10000 test images x 5 severities, concatenated
    in order of increasing severity. labels.npy is the same 10000 labels
    tiled 5 times.
    """
    def __init__(self, corruption_dir, corruption_name, severity, transform):
        images_all = np.load(os.path.join(corruption_dir, f'{corruption_name}.npy'))
        labels_all = np.load(os.path.join(corruption_dir, 'labels.npy'))
        start = (severity - 1) * 10000
        end = severity * 10000
        self.images = images_all[start:end]
        self.labels = labels_all[start:end]
        self.transform = transform

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        img = self.images[idx]  # HWC uint8
        img = self.transform(img) if not isinstance(img, np.ndarray) else self.transform(
            torchvision.transforms.functional.to_pil_image(img)
        )
        return img, int(self.labels[idx])


def make_loaders(train_transform, batch_size=128):
    train_set = torchvision.datasets.CIFAR10(
        root=DRIVE_ROOT, train=True, download=True, transform=train_transform)
    test_set = torchvision.datasets.CIFAR10(
        root=DRIVE_ROOT, train=False, download=True, transform=transform_test)
    train_loader = DataLoader(train_set, batch_size=batch_size, shuffle=True,
                               num_workers=2, pin_memory=True)
    test_loader = DataLoader(test_set, batch_size=256, shuffle=False,
                              num_workers=2, pin_memory=True)
    return train_loader, test_loader


def make_ood_loaders(batch_size=256):
    loaders = {}
    for c in CORRUPTIONS:
        ds = CIFAR10CDataset(CIFAR10C_DIR, c, SEVERITY, transform_test)
        loaders[c] = DataLoader(ds, batch_size=batch_size, shuffle=False,
                                 num_workers=2, pin_memory=True)
    return loaders

# %% [MODEL] ResNet-CIFAR (ResNet-18 adapted for 32x32 inputs) --------------
class BasicBlock(nn.Module):
    expansion = 1

    def __init__(self, in_planes, planes, stride=1):
        super().__init__()
        self.conv1 = nn.Conv2d(in_planes, planes, 3, stride, 1, bias=False)
        self.bn1 = nn.BatchNorm2d(planes)
        self.conv2 = nn.Conv2d(planes, planes, 3, 1, 1, bias=False)
        self.bn2 = nn.BatchNorm2d(planes)
        self.shortcut = nn.Sequential()
        if stride != 1 or in_planes != planes * self.expansion:
            self.shortcut = nn.Sequential(
                nn.Conv2d(in_planes, planes * self.expansion, 1, stride, bias=False),
                nn.BatchNorm2d(planes * self.expansion),
            )

    def forward(self, x):
        out = F.relu(self.bn1(self.conv1(x)))
        out = self.bn2(self.conv2(out))
        out += self.shortcut(x)
        return F.relu(out)


class ResNetCIFAR(nn.Module):
    """Standard 'ResNet-18 for CIFAR' adaptation: 3x3 stride-1 stem, no
    max-pool (full-size ResNet-18 downsamples too aggressively for 32x32
    inputs)."""
    def __init__(self, num_blocks=(2, 2, 2, 2), num_classes=10):
        super().__init__()
        self.in_planes = 64
        self.conv1 = nn.Conv2d(3, 64, 3, 1, 1, bias=False)
        self.bn1 = nn.BatchNorm2d(64)
        self.layer1 = self._make_layer(64, num_blocks[0], 1)
        self.layer2 = self._make_layer(128, num_blocks[1], 2)
        self.layer3 = self._make_layer(256, num_blocks[2], 2)
        self.layer4 = self._make_layer(512, num_blocks[3], 2)
        self.linear = nn.Linear(512, num_classes)

    def _make_layer(self, planes, num_blocks, stride):
        strides = [stride] + [1] * (num_blocks - 1)
        layers = []
        for s in strides:
            layers.append(BasicBlock(self.in_planes, planes, s))
            self.in_planes = planes
        return nn.Sequential(*layers)

    def forward(self, x):
        out = F.relu(self.bn1(self.conv1(x)))
        out = self.layer1(out)
        out = self.layer2(out)
        out = self.layer3(out)
        out = self.layer4(out)
        out = F.adaptive_avg_pool2d(out, 1).flatten(1)
        return self.linear(out)


def resnet18_cifar():
    return ResNetCIFAR(num_blocks=(2, 2, 2, 2))

# %% [TRAIN] ERM training loop with checkpointing ----------------------------
def train_model(run_name, train_transform, epochs=20, lr=0.1, resume=True):
    """Trains one model under ERM. Checkpoints every epoch to Drive so a
    Colab disconnect only costs you the current epoch, not the whole run."""
    ckpt_path = os.path.join(CKPT_DIR, f'{run_name}.pt')
    train_loader, test_loader = make_loaders(train_transform)

    model = resnet18_cifar().to(DEVICE)
    optimizer = torch.optim.SGD(model.parameters(), lr=lr, momentum=0.9,
                                 weight_decay=5e-4)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)
    criterion = nn.CrossEntropyLoss()

    start_epoch = 0
    if resume and os.path.exists(ckpt_path):
        ckpt = torch.load(ckpt_path, map_location=DEVICE)
        model.load_state_dict(ckpt['model'])
        optimizer.load_state_dict(ckpt['optimizer'])
        scheduler.load_state_dict(ckpt['scheduler'])
        start_epoch = ckpt['epoch'] + 1
        print(f"[{run_name}] Resumed from epoch {start_epoch}")

    for epoch in range(start_epoch, epochs):
        model.train()
        t0 = time.time()
        running_loss, correct, total = 0.0, 0, 0
        for imgs, labels in train_loader:
            imgs, labels = imgs.to(DEVICE), labels.to(DEVICE)
            optimizer.zero_grad()
            out = model(imgs)
            loss = criterion(out, labels)
            loss.backward()
            optimizer.step()
            running_loss += loss.item() * imgs.size(0)
            correct += (out.argmax(1) == labels).sum().item()
            total += imgs.size(0)
        scheduler.step()

        train_acc = correct / total
        print(f"[{run_name}] epoch {epoch+1}/{epochs} "
              f"loss={running_loss/total:.4f} acc={train_acc:.4f} "
              f"({time.time()-t0:.1f}s)")

        torch.save({
            'model': model.state_dict(),
            'optimizer': optimizer.state_dict(),
            'scheduler': scheduler.state_dict(),
            'epoch': epoch,
        }, ckpt_path)

    return model, test_loader


# %% [EVAL] Accuracy on ID and OOD sets --------------------------------------
@torch.no_grad()
def evaluate(model, loader):
    model.eval()
    correct, total = 0, 0
    for imgs, labels in loader:
        imgs, labels = imgs.to(DEVICE), labels.to(DEVICE)
        out = model(imgs)
        correct += (out.argmax(1) == labels).sum().item()
        total += imgs.size(0)
    return correct / total


def full_eval(model, id_test_loader, ood_loaders):
    results = {'clean': evaluate(model, id_test_loader)}
    for name, loader in ood_loaders.items():
        results[name] = evaluate(model, loader)
    return results

# %% [RUN] Train both arms, evaluate, save results ---------------------------
EPOCHS = 20  # ~5-10 min/epoch on a T4 for this model size; adjust if slow

ood_loaders = make_ood_loaders()

print("=== Training baseline (mild augmentation) ===")
model_baseline, id_test_loader = train_model(
    'baseline', transform_train_baseline, epochs=EPOCHS)
results_baseline = full_eval(model_baseline, id_test_loader, ood_loaders)

print("=== Training augmented (stronger augmentation, the mitigation) ===")
model_augmented, _ = train_model(
    'augmented', transform_train_augmented, epochs=EPOCHS)
results_augmented = full_eval(model_augmented, id_test_loader, ood_loaders)

# Save raw results to Drive
all_results = {'baseline': results_baseline, 'augmented': results_augmented,
               'severity': SEVERITY, 'corruptions': CORRUPTIONS}
with open(os.path.join(RESULTS_DIR, 'results.json'), 'w') as f:
    json.dump(all_results, f, indent=2)

print(json.dumps(all_results, indent=2))

# %% [FIGURE] Bar chart for the report ---------------------------------------
import matplotlib.pyplot as plt

import json, os

DRIVE_ROOT = '/content/drive/MyDrive/data603_hw1'
RESULTS_DIR = os.path.join(DRIVE_ROOT, 'results')

with open(os.path.join(RESULTS_DIR, 'results.json')) as f:
    all_results = json.load(f)

results_baseline = all_results['baseline']
results_augmented = all_results['augmented']
CORRUPTIONS = all_results['corruptions']
SEVERITY = all_results['severity']

print(results_baseline)
print(results_augmented)

conditions = ['clean'] + CORRUPTIONS
baseline_accs = [results_baseline[c] for c in conditions]
augmented_accs = [results_augmented[c] for c in conditions]

fig, ax = plt.subplots(figsize=(7, 5))
bars = ax.bar(conditions, baseline_accs, color='#4C72B0')
ax.set_xticklabels(conditions, rotation=20)
ax.set_ylabel('Test accuracy')
ax.set_title(f'Baseline model: ID vs OOD accuracy (CIFAR-10-C, severity={SEVERITY})')
ax.set_ylim(0, 1)
# label each bar with its value for readability at report size
for bar, acc in zip(bars, baseline_accs):
    ax.text(bar.get_x() + bar.get_width()/2, acc + 0.02, f'{acc:.2f}',
             ha='center', fontsize=9)
plt.tight_layout()
baseline_fig_path = os.path.join(RESULTS_DIR, 'baseline_id_vs_ood_accuracy.png')
plt.savefig(baseline_fig_path, dpi=150)
plt.show()
print(f"Baseline-only figure saved to {baseline_fig_path}")

# Table 2
conditions = ['clean'] + CORRUPTIONS
baseline_accs = [results_baseline[c] for c in conditions]
augmented_accs = [results_augmented[c] for c in conditions]

x = np.arange(len(conditions))
width = 0.35

fig, ax = plt.subplots(figsize=(8, 5))
ax.bar(x - width/2, baseline_accs, width, label='Baseline (mild aug)')
ax.bar(x + width/2, augmented_accs, width, label='Augmented (mitigation)')
ax.set_xticks(x)
ax.set_xticklabels(conditions, rotation=20)
ax.set_ylabel('Test accuracy')
ax.set_title(f'ID vs OOD accuracy (CIFAR-10-C, severity={SEVERITY})')
ax.legend()
ax.set_ylim(0, 1)
plt.tight_layout()
fig_path = os.path.join(RESULTS_DIR, 'id_vs_ood_accuracy.png')
plt.savefig(fig_path, dpi=150)
plt.show()
print(f"Figure saved to {fig_path}")

# %% [TABLE] Print a markdown table you can paste straight into the report --
print("\n| Condition | Baseline acc | Augmented acc | Delta |")
print("|---|---|---|---|")
for c in conditions:
    b, a = results_baseline[c], results_augmented[c]
    print(f"| {c} | {b:.3f} | {a:.3f} | {a-b:+.3f} |")